### ISSUE TITLE
Hoog en specifiek aantal individueën voor 3 occurrences

### ISSUE THREAD

**Issue by peterdesmet** [inbo/natuurpunt-exoten-occurrences#1]
Volgende waarnemingen hebben een hoog en specifiek aantal individueën. Aanpassen?

https://waarnemingen.be/observation/290965200: 5566551
https://waarnemingen.be/observation/276024661: 22224241
https://waarnemingen.be/observation/290550388: 1001001

**Comment by karingielen** [comment]
Hoornaars al aangepast...

**Comment by karingielen** [comment]
ik zie dat ook de mot is aangepast (maar misschien nog niet in dump van deze week)...
