### ISSUE TITLE
Ongekende waarde `flight_interception_trap`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/natuurpunt-exoten-occurrences#10]
11 waarnemingen hebben de waarde `flight_interception_trap` voor volgende velden:

- identificationRemarks
- occurrenceRemarks
- samplingProtocol

Aanpassen naar:

- identificationRemarks: (default)
- occurrenceRemarks: (default)
- samplingProtocol: `flight interception trap` (cf. `colour trap` en andere traps)

**Comment by karingielen** [comment]
Aangepast! Normaal tegen woe. in orde...
