### ISSUE TITLE
field "ontsnapt" pushed to gbif?

### ISSUE THREAD

**Issue by timadriaens** [inbo/natuurpunt-exoten-occurrences#11]
here is an issue encountered whilst planning field work on species for RadIUS with @fleurpet many locations are in a captive/cultivated setting (gardens, captivity etc.) which is super useful to know (and preferably we would also like to have this filtering option in the early alert system).

So, is this checkbox with `ontsnapt` mapped to GBIF? If not, can we make that happen? To note we absolutely want these records as they are informative on size of captive population, pathways, introduction efforts etc. How is this dealt with? Sorry if this was already taken into account @peterdesmet . As you know we are also trying to convince iNaturalist to publish the captive/cultivate records in a separate dataset.

**Comment by peterdesmet** [comment]
With the `ontsnapt` checkbox, do you mean information that the observer indicated **at observation level**? That info is not mapped to Darwin Core as it was deemed confusing with the status **at species level** (which is used as a filter to include/exclude records in the exoten datasets).

**Comment by peterdesmet** [comment]
Yeah, that info is not included in the Darwin Core mapping, but the observation is (in contrast with iNat).

**Comment by timadriaens** [comment]
Ok, i chewed on it and I think in general that is ok because

- the checkbox is not consistently checked by observers
-  we dont want to miss any potentially relevant records 
- from a management point of view tackling what is in cultivated setting (so at the source of future invasions) makes a lot of sense
- the checkbox is not consistently applied/asked by validators (cf. what does 'ontsnapt' actually mean, 'captive/cultivated' is much more clear, you could brand all garden escapes that are encountered in the wild as 'ontsnapt' or take a more conservative approach and only consider those where there is still a clear link with the cultivated setting for instance a dumped garden compost heap or a nearby urban planting)
- for the early alert system, users can always go to the original record and see for themselves whether the observation was branded as an escape
