### ISSUE TITLE
Waarde `microscopic_examination` terug in identificationRemarks

### ISSUE THREAD

**Issue by peterdesmet** [inbo/natuurpunt-exoten-occurrences#16]
Eén record (https://waarnemingen.be/observation/309188920) heeft de waarde `microscopic_examination` in identificationRemarks. Dit is in 2019 al [eens voorgekomen](https://github.com/inbo/data-publication-natuurpunt/issues/198) en toen opgelost. De juiste waarde is `microscopic examination` (wat 134 waarden effectief hebben).

**Comment by karingielen** [comment]
Opgelost.
