### ISSUE TITLE
Foute waarde `melanistic`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/natuurpunt-exoten-occurrences#2]
https://waarnemingen.be/observation/273868883 heeft `melanistic` als dynamicProperties, lifeStage, occurrenceRemarks, reproductiveCondition. Het is me niet duidelijk hoe deze juist te mappen? Als occurrenceRemark?

- dynamicProperties: (default)
- lifeStage: ?
- occurrenceRemarks: ?
- reproductiveCondition: ?

**Comment by karingielen** [comment]
Dat gaat over kleed van de 4 jongen! Lijkt me cfr 1st summer plumage enz bij Occ remarks te mogen komen? Maar vraag me wel af of dit effectief wel klopt hier. Ik vraag het eerst nog even aan Gerald (Driessens)...

**Comment by peterdesmet** [comment]
Ja, lijkt me dan het best als volgt:

- dynamicProperties: (default)
- lifeStage: (default)
- occurrenceRemarks: melanistic
- reproductiveCondition: (default)

**Comment by karingielen** [comment]
Melanistisch moest "pullus" zijn, dus opgelost...

**Comment by peterdesmet** [comment]
Waarneming heeft nu lifeStage `chick`, verder geen occurrenceRemarks, dynamicProperties, reproductiveCondition
