### ISSUE TITLE
Foute waarde `genitals_examined`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/natuurpunt-exoten-occurrences#4]
De volgende waarnemingen hebben de foute waarde `genitals_examined` voor identificationRemarks, occurrenceRemarks, samplingProtocol

https://waarnemingen.be/observation/290748512
https://waarnemingen.be/observation/280621157
https://waarnemingen.be/observation/292916001
https://waarnemingen.be/observation/292915915

Aanpassen naar:

- identificationRemarks: nieuwe waarde `genitals examined` of `genitalia examination` (cf. microscopic examination)
- occurrenceRemarks: (default)
- samplingProtocol: (default)

**Comment by karingielen** [comment]
in orde gebracht.
