### ISSUE TITLE
Foute waarde `led_bucket`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/natuurpunt-exoten-occurrences#5]
https://waarnemingen.be/observation/290471460 heeft de foute waarde `led_bucket` voor identificationRemarks, occurrenceRemarks, samplingProtocol

Aanpassen naar:

- identificationRemarks: (welke waarde kiezen we hiervoor?)
- occurrenceRemarks: (default)
- samplingProtocol: (default)

**Comment by karingielen** [comment]
In Kleed/gedrag excel staat deze al... Om een of andere reden nieuwe code gekregen in wbe. Ik pas aan!

**Comment by peterdesmet** [comment]
Record https://waarnemingen.be/observation/290471460 heeft nu `light trap` voor samplingProtocol en `attracted to light` for occurrenceRemarks 👍
