### ISSUE TITLE
Hoog en specifiek aantal individueën Reuzenbalsemien

### ISSUE THREAD

**Issue by peterdesmet** [inbo/natuurpunt-exoten-occurrences#6]
Deze waarneming van Reuzenbalsemien https://waarnemingen.be/observation/275231186/ heeft `2147483647` aantal individueën. De telmethode is `gezien niet geteld`. Het aantal lijkt dan wel heel hoog en specifiek. Aanpassen?

**Comment by karingielen** [comment]
Is intussen opgelost (mss nog niet in dump van deze week...)

**Comment by peterdesmet** [comment]
Komt inderdaad niet meer voor. De enige vreemde waarde is 1000000000 (1 miljard), maar is ten minste afgerond.
