### ISSUE TITLE
Verkeerde rank voor Myriophyllum rubricaule

### ISSUE THREAD

**Issue by peterdesmet** [inbo/natuurpunt-exoten-occurrences#8]
Oorspronkelijk gerapporteerd in 2022, maar nog niet opgelost. `Myriophyllum rubricaule` staat verkeerdelijk als taxonRank cultivar ipv species aangeduid in de export. Ook al lijkt het in de databank in orde:

![184881400-d61c5903-9c8f-4bdf-aaa8-174bc4625e06](https://github.com/inbo/exoten-natuurpunt-occurrences/assets/600993/b0c041b3-51eb-4436-9cd0-3ede25e07c5e)

**Comment by karingielen** [comment]
Die is ooit hardcoded op cultivar geplaatst... Blijkbaar is er intussen een beweging geweest om dat te veranderen. 
Ik haal de hardcoding er in ieder geval terug uit...
