### ISSUE TITLE
Verkeerde rank voor `Juncus effusus (cultivar)` en `Rubus canadensis`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/natuurpunt-exoten-occurrences#9]
Oorpronkelijk gerapporteerd in 2021 en meeste is opgelost, maar volgende taxa hebben de verkeerde rank in de laatste export:

- [ ] `https://waarnemingen.be/species/1033951,Juncus effusus (cultivar),variety,Pitrus (cultivar)`
- [ ] `https://waarnemingen.be/species/596224,Rubus canadensis,subspecies,Spitsbraam`

**Comment by karingielen** [comment]
Kan ik dan nog ergens terugvinden naar wat dat moet gewijzigd worden? Nl ev naar dat issue van 2021? Want ik zie geen manier om dat ergens terug te openen?

**Comment by peterdesmet** [comment]
Dag Karin, de issue van 2021 is nu private, maar de context heb je niet nodig. Het gaat enkel om de 2 bovenstaande taxa, die een verkeerde rank hebben:

- `Juncus effusus (cultivar)` zou logischerwijs rank `cultivar` moeten krijgen ipv `variety`
- `Rubus canadensis` zou logischerwijs rank `species` moeten krijgen ipv `subspecies`

**Comment by karingielen** [comment]
Rubus canadensis is effectief als 'soort' goedgekeurd door de specialisten en aangepast in waarnemingen.be. Dus onze dump van volgende week zou dit meteen dan ook zo moeten oppikken...
